

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "ExpenseTracker"
      PGDATA: /var/lib/postgresql/appdata
    volumes:
      - postgres_data:/var/lib/postgresql/appdata
    ports:
      - "5432:5432"

volumes:
  postgres_data:










