
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "ExpenseTracker"
      PGDATA: /var/lib/postgresql/appdata
    volumes:
      - ./appdata:/var/lib/postgresql/appdata
    ports:
      - "5432:5432"










