INSERT INTO "Category" (name) VALUES ('Food');
INSERT INTO "Category" (name) VALUES ('Transportation');
INSERT INTO "Category" (name) VALUES ('Utilities');
INSERT INTO "Category" (name) VALUES ('Housing');
INSERT INTO "Category" (name) VALUES ('Healthcare');
INSERT INTO "Category" (name) VALUES ('Entertainment');
INSERT INTO "Category" (name) VALUES ('Education');
INSERT INTO "Category" (name) VALUES ('Clothing');
INSERT INTO "Category" (name) VALUES ('Personal Care');
INSERT INTO "Category" (name) VALUES ('Miscellaneous');